### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by stefxx** [EishaV/Desktop-App#4]
Hi, thanks for your great program. Like it a lot. However, I can login (Anmelden) but I cannot connect (Verbinden). I get the error below:

uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException: Exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' was thrown.
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(Byte[] msgBytes, Int32 timeout)
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod)
   at DesktopApp.LsClient.Start(String broker, String uuid, String board, String mac, Boolean first) in C:\Users\abc\Downloads\Desktop-App-master\Desktop-App-master\DesktopApp\LsClient.cs:line 495

Any idea why? Thanks!

**Comment by stefxx** [comment]
Hi, any thoughts on this? Thanks!

**Comment by mapa0402** [comment]
I can't connect either. Error 401, what should CliSec be exactly?

**Comment by EishaV** [comment]
Thats user errors, please ask on Roboter-Forum.
